version: '3.3'

services:

  web:
    container_name: web
    build:
      context: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
