# Generated by Django 4.1.6 on 2023-02-13 18:30

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='uploads/source'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aiff', 'wav'], message='Invalid extension. Only mp3, wav or aiff is acceptable')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
