# Generated by Django 4.1.6 on 2023-03-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='link',
            field=models.URLField(max_length=1024, null=True, unique=True, verbose_name='sample url'),
        ),
    ]
