# Generated by Django 4.1.6 on 2023-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='author',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
