# Generated by Django 4.1.6 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='Program Core', max_length=128)),
                ('pages_number', models.IntegerField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('parse_period', models.CharField(choices=[('Every hour', 'Every Hour'), ('Every 3 hours', 'Three Hours'), ('Every 6 hours', 'Six Hours'), ('Once a day', 'Once A Day'), ('Once a week', 'Once A Week')], default='Once a day', max_length=128)),
                ('additional_phrase', models.CharField(blank=True, max_length=128, null=True)),
                ('in_process', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Core',
            },
        ),
    ]
